Eshopper/Areas/Admin/Controllers/brandController.cs
using Eshopper.Areas.Admin.Models.Entites;
using Eshopper.Areas.Admin.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eshopper.Areas.Admin.Controllers
{
    public class brandController : Controller
    {
        private brandRepository mngr;
        public brandController()
        {
            mngr = new brandRepository(new Models.AppDbContext.Context());
        }
        // GET: Admin/category
        public ActionResult Index()
        {
            return View(mngr.getAll());
        }
        public ActionResult Create()
        {
            return View();
        }
        // Kaydetme 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Brand model)
        {
            if (ModelState.IsValid)
                mngr.Save(model);
            return RedirectToAction("/");
        }
        public ActionResult Edit(int id)
        {
            return View(mngr.Get(id));
        }
        //değiştirme
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Brand model)
        {
            if (ModelState.IsValid)
                mngr.Update(model);
            return RedirectToAction("/");
        }
        public ActionResult Delete(int id)
        {
            return View(mngr.Get(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCategory(int id)
        {
            if (ModelState.IsValid)
                mngr.Delete(mngr.Get(id));
            return RedirectToAction("/");
        }
    }
}

Eshopper/Areas/Admin/Controllers/categoryController.cs
using Eshopper.Areas.Admin.Models.Entites;
using Eshopper.Areas.Admin.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eshopper.Areas.Admin.Controllers
{
    public class categoryController : Controller
    {
        private categoryRepository mngr;
        public categoryController()
        {
            mngr = new categoryRepository(new Models.AppDbContext.Context());
        }
        // GET: Admin/category
        public ActionResult Index()
        {
            return View(mngr.getAll());
        }
        public ActionResult Create()
        {
            return View();
        }
        // Kaydetme 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(category model)
        {
            if (ModelState.IsValid)
                mngr.Save(model);
            return RedirectToAction("/");
        }
        public ActionResult Edit(int id)
        {
            return View(mngr.Get(id));
        }
        //değiştirme
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(category model)
        {
            if (ModelState.IsValid)
                mngr.Update(model);
            return RedirectToAction("/");
        }
        public ActionResult Delete(int id)
        {
            return View(mngr.Get(id));
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCategory(int id)
        {
            if(ModelState.IsValid)
                mngr.Delete(mngr.Get(id));
            return RedirectToAction("/");
        }
    }
}

Eshopper/Areas/Admin/Controllers/productController.cs
using Eshopper.Areas.Admin.Models.Entites;
using Eshopper.Areas.Admin.Models.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eshopper.Areas.Admin.Controllers
{
    public class productController : Controller
    {
        private productRepository mngr;
        private brandRepository bmngr;
        private categoryRepository cmngr;
        public productController()
        {
            mngr = new productRepository(new Models.AppDbContext.Context());
            bmngr = new brandRepository(new Models.AppDbContext.Context());
            cmngr = new categoryRepository(new Models.AppDbContext.Context());
        }
        // GET: Admin/category
        public ActionResult Index()
        {
            return View(mngr.getAll());
        }
        public ActionResult Create()
        {
            ViewBag.Brands = bmngr.getAll();
            ViewBag.Categories = cmngr.getAll();
            return View();
        }
        // Kaydetme 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product model, HttpPostedFileBase image1)
        {
            model.created = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (image1 != null)
                {
                    using (var br = new BinaryReader(image1.InputStream))
                    {
                        var data = br.ReadBytes(image1.ContentLength);
                         model.img = data;
                    }

                }

                mngr.Save(model);
            }
            return RedirectToAction("/");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Brands = bmngr.getAll();
            ViewBag.Categories = cmngr.getAll();
            return View(mngr.Get(id));
        }
        //değiştirme
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product model, HttpPostedFileBase image1)
        {
            model.created = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (image1 != null)
                {
                    using (var br = new BinaryReader(image1.InputStream))
                    {
                        var data = br.ReadBytes(image1.ContentLength);
                        model.img = data;
                    }
                }
                mngr.Update(model);
            }
            return RedirectToAction("/");
        }
        public ActionResult Delete(int id)
        {
            return View(mngr.Get(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProduct(int id)
        {
            if (ModelState.IsValid)
                mngr.Delete(mngr.Get(id));
            return RedirectToAction("/");
        }
    }
}

Eshopper/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Eshopper/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="~/Areas/Admin/Asset/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="~/Areas/Admin/Asset/css/styles.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <!-- Logo -->
                    <div class="logo">
                        <h1><a href="index.html">Bootstrap Admin Theme</a></h1>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="input-group form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">Search</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="navbar navbar-inverse" role="banner">
                        <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li><a href="profile.html">Profile</a></li>
                                        <li><a href="login.html">Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-content">
        <div class="row">
            <div class="col-md-2">
                <div class="sidebar content-box" style="display: block;">
                    <ul class="nav">
                        <!-- Main menu -->
                        <li class="current"><a href="@Url.Action("/","category")"><i class="glyphicon glyphicon-home"></i> Kategoriler</a></li>
                        <li><a href="@Url.Action("/","brand")"><i class="glyphicon glyphicon-calendar"></i> Markalar</a></li>
                        <li><a href="@Url.Action("/","product")"><i class="glyphicon glyphicon-stats"></i> Ürünler</a></li>
     
                        
                    </ul>
                </div>
            </div>
            <div class="col-md-10">

                <div class="row">
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>
    <footer>
        <div class="container">

            <div class="copy text-center">
                Copyright 2014 <a href='#'>Website</a>
            </div>

        </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Areas/Admin/Asset/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Asset/js/custom.js"></script>
</body>
</html>